

USE NORTHWIND;
GO
SET LANGUAGE 'English'


--1.CONSULTA CON EL FOLIO Y FECHA DE LA ORDEN CUYO AÑO SEA MULTIPLO DE 3 Y EL MES TERMINE CON VOCAL--
SELECT [Folio] = ORDERID, [Ano multiplo] = convert(char(4), datepart(yy,ORDERDATE)), 
[Mes] = convert(char(35), DATENAME(MM,ORDERDATE)) FROM Orders WHERE convert(char(35), DATENAME(MM,ORDERDATE)) LIKE '%[aeiou]'
AND convert(char(4), datepart(yy,ORDERDATE)) % 3 = 0;

--2.CONSULTA CON EL FOLIO DE LA ORDEN, FECHA Y NOMBRE DEL EMPLEADO QUE SE HAYAN REALIZADO LOS DIAS LUNES, MIÉRCOLES Y VIERNES.--

SELECT [Folio] = O.ORDERID, [Ano] = Convert(char(35), DATENAME(DW,O.ORDERDATE)),[Nombre Empleado] = E.FIRSTNAME + ' ' + E.LASTNAME 
FROM Orders O
INNER JOIN Employees E ON E.EmployeeID = O.EmployeeID  
WHERE convert(char(35), DATENAME(DW,O.ORDERDATE)) like 'Monday' OR
	  convert(char(35), DATENAME(DW,O.ORDERDATE)) LIKE 'wednesday'	OR 
		convert(char(35), DATENAME(DW,O.ORDERDATE)) like 'Thursday'

--3-- CONSULTA CON LAS PRIMERAS 10 ORDENES DE 1997--
SELECT TOP 10 [FOLIO] = ORDERID FROM ORDERS WHERE convert(char(35), DATENAME(YY,ORDERDATE)) LIKE '1997'

SELECT FIRSTNAME,ReportsTo FROM Employees;

--4.- CONSULTA CON EL NOMBRE EMPLEADOS Y NOMBRE DE SU JEFE QUE VIVAN EN UN BLVD Y NO TENGAN UNA REGION ASIGNADA. --
SELECT [Nombre Completo] = E.FIRSTNAME + ' ' + E.LASTNAME,[Nombre Jefe] = F.FIRSTNAME + ' ' + F.LASTNAME, E.ReportsTo  FROM Employees E
INNER JOIN Employees F ON F.EmployeeID = E.ReportsTo WHERE E.Address LIKE '%Blvd%' and E.Region IS NULL AND
F.Address LIKE '%Blvd%' and F.Region IS NULL;



--5.- CONSULTA CON EL NOMBRE DEL PRODUCTO, NOMBRE DEL PROVEEDOR Y NOMBRE DE LA CATEGORIA.--
--MOSTRAR SOLO LOS PROVEEDORES QUE NO TENGAN FAX Y QUE SI TENGAN HOMEPAGE.--
SELECT [Nombre del producto] = P.PRODUCTNAME, [Nombre del proovedor] =S.CONTACTNAME,
[Nombre de la categoria] = C.CATEGORYNAME FROM PRODUCTS P INNER JOIN SUPPLIERS S ON S.SUPPLIERID = P.SUPPLIERID INNER JOIN CATEGORIES C ON
C.CATEGORYID = P.CATEGORYID WHERE S.FAX IS NULL AND S.HomePage IS NOT NULL;

--6.- CONSULTA CON EL NOMBRE DEL empleado Y NOMBRE DEL TERRITORIO QUE ATIENDE--
SELECT [Nombre de empleado] = E.FIRSTNAME + ' ' + E.LASTNAME, [Nombre del territorio del empleado]= Y.TerritoryDescription
FROM EmployeeTerritories T INNER JOIN Employees E ON 
E.EmployeeID = T.EMPLOYEEID INNER JOIN Territories Y ON Y.TerritoryID = T.TerritoryID;

--7.- CONSULTA CON EL FOLIO DE LA ORDEN, MESES TRANSCURRIDOS DE LA ORDEN, NOMBRE DEL EMPLEADO QUE HIZO LA ORDEN--
--MOSTRAR SOLO LAS ORDENES DE LOS EMPLEADOS QUE VIVAN EN EL PAIS “USA” Y QUE EL CODIGO POSTAL CONTENGA UN 2--

SELECT O.ORDERID, [Meses transcurridos desde la orden]=datediff(mm, O.OrderDate, getdate()), [Nombre del empleado]=E.FirstName + ' ' + E.LastName
FROM ORDERS O INNER JOIN Employees E ON E.EmployeeID = O.EmployeeID WHERE E.Country LIKE 'USA' AND E.PostalCode LIKE '%2%';

--8.- CONSULTA CON EL FOLIO DE LA ORDEN, NOMBRE DEL PRODUCTO E IMPORTE DE VENTA.--
--MOSTRAR SOLO LAS ORDENES DE LOS PRODUCTOS CUYA CATEGERIA CONTENGA DOS VOCALES SEGUIDAS.--
SELECT  [Folio] =  O.ORDERID, [Nombre del producto] =  P.ProductName, [Importe] = D.Quantity * D.Quantity 
FROM ORDERS O INNER JOIN [Order Details] D ON D.OrderID = O.OrderID
INNER JOIN PRODUCTS P ON P.ProductID = D.ProductID;

--9.- CONSULTA CON EL NOMBRE DEL EMPLEADO, NOMBRE DEL TERRITORIO QUE ATIENDE.--
--MOSTRAS SOLO LOS EMPLEADOS QUE EL TERRITORIO ESTE EN UNA REGION QUE EMPIECE CON VOCAL Y TERMINE CON CONSONANTE.--
SELECT [Nombre de empleado] = E.FIRSTNAME + ' ' + E.LASTNAME, [Nombre del territorio] = T.TerritoryDescription,
R.RegionDescription
FROM Employees E INNER JOIN EmployeeTerritories Y ON Y.EmployeeID = E.EmployeeID INNER JOIN
Territories T ON T.TerritoryID = Y.TerritoryID INNER JOIN Region R ON R.RegionID = T.RegionID
WHERE R.RegionDescription LIKE '[AEIOU]%' AND R.RegionDescription LIKE '%[^aeiou]';

--10.- CONSULTA CON EL FOLIO DE LA ORDEN, FECHA DE LA ORDEN, NOMBRE DEL EMPLEADO, EDAD QUE TENIA EL EMPLEADO CUANDO HIZO LA ORDEN.--
SELECT O.ORDERID, O.OrderDate, [Nombre de empleado] = E.FIRSTNAME + ' ' + E.LASTNAME,
[Edad cuando se realizo la orden]=datediff(yy,E.BirthDate,O.OrderDate)
FROM ORDERS O INNER JOIN EMPLOYEES E ON E.EmployeeID = O.EmployeeID;